//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notification
{
    using System;
    using System.Collections.Generic;
    
    public partial class simulation
    {
        public string id { get; set; }
        public Nullable<double> loanAmount { get; set; }
        public Nullable<double> loanTerm { get; set; }
        public string email { get; set; }
        public string bank { get; set; }
        public string category { get; set; }
        public Nullable<double> results { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
